/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_BasicSafetyMessage_regExt_H_
#define	_BasicSafetyMessage_regExt_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LongitudinalControlExtension.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BasicSafetyMessage-regExt */
typedef struct BasicSafetyMessage_regExt {
	LongitudinalControlExtension_t	 lce;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicSafetyMessage_regExt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicSafetyMessage_regExt;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicSafetyMessage_regExt_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicSafetyMessage_regExt_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _BasicSafetyMessage_regExt_H_ */
#include <asn_internal.h>
