/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_BroadRegion_H_
#define	_BroadRegion_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Polygon.h"
#include "Circle.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BroadRegion_PR {
	BroadRegion_PR_NOTHING,	/* No components present */
	BroadRegion_PR_polygon,
	BroadRegion_PR_circle
	/* Extensions may appear below */
	
} BroadRegion_PR;

/* BroadRegion */
typedef struct BroadRegion {
	BroadRegion_PR present;
	union BroadRegion_u {
		Polygon_t	 polygon;
		Circle_t	 circle;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BroadRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BroadRegion;
extern asn_CHOICE_specifics_t asn_SPC_BroadRegion_specs_1;
extern asn_TYPE_member_t asn_MBR_BroadRegion_1[2];
extern asn_per_constraints_t asn_PER_type_BroadRegion_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _BroadRegion_H_ */
#include <asn_internal.h>
