/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAMP-TESTING-REGION"
 * 	found in "CAMP/BSM_V2VI_TDF_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_CAMP_TESTING_REGION_BasicSafetyMessage_regExt_H_
#define	_CAMP_TESTING_REGION_BasicSafetyMessage_regExt_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TestDataFrameV2VI;

/* BasicSafetyMessage-regExt */
typedef struct CAMP_TESTING_REGION_BasicSafetyMessage_regExt {
	struct TestDataFrameV2VI	*tdf	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAMP_TESTING_REGION_BasicSafetyMessage_regExt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMP_TESTING_REGION_BasicSafetyMessage_regExt;
extern asn_SEQUENCE_specifics_t asn_SPC_CAMP_TESTING_REGION_BasicSafetyMessage_regExt_specs_1;
extern asn_TYPE_member_t asn_MBR_CAMP_TESTING_REGION_BasicSafetyMessage_regExt_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TestDataFrameV2VI.h"

#endif	/* _CAMP_TESTING_REGION_BasicSafetyMessage_regExt_H_ */
#include <asn_internal.h>
