/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "CommonContainer.h"

asn_TYPE_member_t asn_MBR_CommonContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CommonContainer, eventInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CommonContainer, regionInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"regionInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_CommonContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CommonContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventInfoat 29 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* regionInfoat 30 */
};
asn_SEQUENCE_specifics_t asn_SPC_CommonContainer_specs_1 = {
	sizeof(struct CommonContainer),
	offsetof(struct CommonContainer, _asn_ctx),
	asn_MAP_CommonContainer_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CommonContainer = {
	"CommonContainer",
	"CommonContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_CommonContainer_tags_1,
	sizeof(asn_DEF_CommonContainer_tags_1)
		/sizeof(asn_DEF_CommonContainer_tags_1[0]), /* 1 */
	asn_DEF_CommonContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_CommonContainer_tags_1)
		/sizeof(asn_DEF_CommonContainer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CommonContainer_1,
	2,	/* Elements count */
	&asn_SPC_CommonContainer_specs_1	/* Additional specs */
};

