/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_CongestionInfo_H_
#define	_CongestionInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "RegionInfo.h"
#include "ObstacleDistance.h"
#include "Velocity.h"
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RSMLane;
struct RSMSpeedLimit;

/* CongestionInfo */
typedef struct CongestionInfo {
	BOOLEAN_t	 queueAheadWarning;
	struct RSMLane	*associatedLane	/* OPTIONAL */;
	RegionInfo_t	 startOfQueue;
	ObstacleDistance_t	*lengthOfQueue	/* OPTIONAL */;
	struct RSMSpeedLimit	*speedLimit	/* OPTIONAL */;
	Velocity_t	*averageVehicleSpeed	/* OPTIONAL */;
	BOOLEAN_t	*normalConditions	/* OPTIONAL */;
	IA5String_t	*unexpectedConditionDesc	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CongestionInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CongestionInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_CongestionInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_CongestionInfo_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RSMLane.h"
#include "RSMSpeedLimit.h"

#endif	/* _CongestionInfo_H_ */
#include <asn_internal.h>
