/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "CongestionInfo.h"

static int check_permitted_alphabet_9(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127)) return -1;
	}
	return 0;
}

static int
memb_unexpectedConditionDesc_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 100)
		 && !check_permitted_alphabet_9(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_unexpectedConditionDesc_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..100)) */};
static asn_per_constraints_t asn_PER_memb_unexpectedConditionDesc_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_CONSTRAINED,	 7,  7,  1,  100 }	/* (SIZE(1..100)) */,
	0, 0	/* No PER character map necessary */
};
asn_TYPE_member_t asn_MBR_CongestionInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CongestionInfo, queueAheadWarning),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"queueAheadWarning"
		},
	{ ATF_POINTER, 1, offsetof(struct CongestionInfo, associatedLane),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSMLane,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associatedLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CongestionInfo, startOfQueue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"startOfQueue"
		},
	{ ATF_POINTER, 5, offsetof(struct CongestionInfo, lengthOfQueue),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObstacleDistance,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lengthOfQueue"
		},
	{ ATF_POINTER, 4, offsetof(struct CongestionInfo, speedLimit),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSMSpeedLimit,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speedLimit"
		},
	{ ATF_POINTER, 3, offsetof(struct CongestionInfo, averageVehicleSpeed),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Velocity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"averageVehicleSpeed"
		},
	{ ATF_POINTER, 2, offsetof(struct CongestionInfo, normalConditions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"normalConditions"
		},
	{ ATF_POINTER, 1, offsetof(struct CongestionInfo, unexpectedConditionDesc),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ &asn_OER_memb_unexpectedConditionDesc_constr_9, &asn_PER_memb_unexpectedConditionDesc_constr_9,  memb_unexpectedConditionDesc_constraint_1 },
		0, 0, /* No default value */
		"unexpectedConditionDesc"
		},
};
static const int asn_MAP_CongestionInfo_oms_1[] = { 1, 3, 4, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_CongestionInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CongestionInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* queueAheadWarningat 398 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* associatedLaneat 399 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* startOfQueueat 400 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* lengthOfQueueat 401 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* speedLimitat 403 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* averageVehicleSpeedat 404 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* normalConditionsat 405 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* unexpectedConditionDescat 406 */
};
asn_SEQUENCE_specifics_t asn_SPC_CongestionInfo_specs_1 = {
	sizeof(struct CongestionInfo),
	offsetof(struct CongestionInfo, _asn_ctx),
	asn_MAP_CongestionInfo_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_CongestionInfo_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CongestionInfo = {
	"CongestionInfo",
	"CongestionInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_CongestionInfo_tags_1,
	sizeof(asn_DEF_CongestionInfo_tags_1)
		/sizeof(asn_DEF_CongestionInfo_tags_1[0]), /* 1 */
	asn_DEF_CongestionInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_CongestionInfo_tags_1)
		/sizeof(asn_DEF_CongestionInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CongestionInfo_1,
	8,	/* Elements count */
	&asn_SPC_CongestionInfo_specs_1	/* Additional specs */
};

