/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_CurveContainer_H_
#define	_CurveContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SpeedAdvice.h"
#include "FrictCoef.h"
#include "SurfaceCondition.h"
#include "Material.h"
#include "Radius.h"
#include "BankAngle.h"
#include "Activity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AreaType;

/* CurveContainer */
typedef struct CurveContainer {
	SpeedAdvice_t	 advisorySpeed;
	FrictCoef_t	*frictCoef	/* OPTIONAL */;
	SurfaceCondition_t	*surfaceCondition	/* OPTIONAL */;
	Material_t	*material	/* OPTIONAL */;
	Radius_t	*minRadius	/* OPTIONAL */;
	BankAngle_t	*bankAngle	/* OPTIONAL */;
	Activity_t	*obstaclePresent	/* OPTIONAL */;
	Activity_t	*reducedVisibility	/* OPTIONAL */;
	struct AreaType	*curveRegion	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurveContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurveContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_CurveContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_CurveContainer_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AreaType.h"

#endif	/* _CurveContainer_H_ */
#include <asn_internal.h>
