/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "DynamicInfoContainer.h"

static int check_permitted_alphabet_8(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127)) return -1;
	}
	return 0;
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_dmsSignString_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 100)
		 && !check_permitted_alphabet_8(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_congestionInfo_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 30)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_priority_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_priority_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_congestionInfo_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..30)) */};
static asn_per_constraints_t asn_PER_type_congestionInfo_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  30 }	/* (SIZE(1..30)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_dmsSignString_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..100)) */};
static asn_per_constraints_t asn_PER_memb_dmsSignString_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_CONSTRAINED,	 7,  7,  1,  100 }	/* (SIZE(1..100)) */,
	0, 0	/* No PER character map necessary */
};
static asn_oer_constraints_t asn_OER_memb_congestionInfo_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..30)) */};
static asn_per_constraints_t asn_PER_memb_congestionInfo_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  30 }	/* (SIZE(1..30)) */,
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_priority_value2enum_2[] = {
	{ 0,	12,	"low-priority" },
	{ 1,	15,	"medium-priority" },
	{ 2,	13,	"high-priority" },
	{ 3,	8,	"critical" }
};
static const unsigned int asn_MAP_priority_enum2value_2[] = {
	3,	/* critical(3) */
	2,	/* high-priority(2) */
	0,	/* low-priority(0) */
	1	/* medium-priority(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_priority_specs_2 = {
	asn_MAP_priority_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_priority_enum2value_2,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_priority_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_priority_2 = {
	"priority",
	"priority",
	&asn_OP_NativeEnumerated,
	asn_DEF_priority_tags_2,
	sizeof(asn_DEF_priority_tags_2)
		/sizeof(asn_DEF_priority_tags_2[0]) - 1, /* 1 */
	asn_DEF_priority_tags_2,	/* Same as above */
	sizeof(asn_DEF_priority_tags_2)
		/sizeof(asn_DEF_priority_tags_2[0]), /* 2 */
	{ &asn_OER_type_priority_constr_2, &asn_PER_type_priority_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_priority_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_congestionInfo_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CongestionInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_congestionInfo_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_congestionInfo_specs_9 = {
	sizeof(struct DynamicInfoContainer__congestionInfo),
	offsetof(struct DynamicInfoContainer__congestionInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_congestionInfo_9 = {
	"congestionInfo",
	"congestionInfo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_congestionInfo_tags_9,
	sizeof(asn_DEF_congestionInfo_tags_9)
		/sizeof(asn_DEF_congestionInfo_tags_9[0]) - 1, /* 1 */
	asn_DEF_congestionInfo_tags_9,	/* Same as above */
	sizeof(asn_DEF_congestionInfo_tags_9)
		/sizeof(asn_DEF_congestionInfo_tags_9[0]), /* 2 */
	{ &asn_OER_type_congestionInfo_constr_9, &asn_PER_type_congestionInfo_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_congestionInfo_9,
	1,	/* Single element */
	&asn_SPC_congestionInfo_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_DynamicInfoContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DynamicInfoContainer, priority),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_priority_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"priority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DynamicInfoContainer, typeOfInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TypeOfDynamicInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"typeOfInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct DynamicInfoContainer, dmsSignString),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ &asn_OER_memb_dmsSignString_constr_8, &asn_PER_memb_dmsSignString_constr_8,  memb_dmsSignString_constraint_1 },
		0, 0, /* No default value */
		"dmsSignString"
		},
	{ ATF_POINTER, 3, offsetof(struct DynamicInfoContainer, congestionInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_congestionInfo_9,
		0,
		{ &asn_OER_memb_congestionInfo_constr_9, &asn_PER_memb_congestionInfo_constr_9,  memb_congestionInfo_constraint_1 },
		0, 0, /* No default value */
		"congestionInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct DynamicInfoContainer, situationalInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SituationalContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"situationalInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct DynamicInfoContainer, incidentsInfo),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IncidentsContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"incidentsInfo"
		},
};
static const int asn_MAP_DynamicInfoContainer_oms_1[] = { 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_DynamicInfoContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DynamicInfoContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* priorityat 373 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* typeOfInfoat 374 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dmsSignStringat 375 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* congestionInfoat 377 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* situationalInfoat 378 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* incidentsInfoat 379 */
};
asn_SEQUENCE_specifics_t asn_SPC_DynamicInfoContainer_specs_1 = {
	sizeof(struct DynamicInfoContainer),
	offsetof(struct DynamicInfoContainer, _asn_ctx),
	asn_MAP_DynamicInfoContainer_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_DynamicInfoContainer_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DynamicInfoContainer = {
	"DynamicInfoContainer",
	"DynamicInfoContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_DynamicInfoContainer_tags_1,
	sizeof(asn_DEF_DynamicInfoContainer_tags_1)
		/sizeof(asn_DEF_DynamicInfoContainer_tags_1[0]), /* 1 */
	asn_DEF_DynamicInfoContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_DynamicInfoContainer_tags_1)
		/sizeof(asn_DEF_DynamicInfoContainer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DynamicInfoContainer_1,
	6,	/* Elements count */
	&asn_SPC_DynamicInfoContainer_specs_1	/* Additional specs */
};

