/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "J2735_201603DA-CAMP.ASN"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_ElevationB_H_
#define	_ElevationB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ElevationB */
typedef long	 ElevationB_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ElevationB_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ElevationB;
asn_struct_free_f ElevationB_free;
asn_struct_print_f ElevationB_print;
asn_constr_check_f ElevationB_constraint;
ber_type_decoder_f ElevationB_decode_ber;
der_type_encoder_f ElevationB_encode_der;
xer_type_decoder_f ElevationB_decode_xer;
xer_type_encoder_f ElevationB_encode_xer;
oer_type_decoder_f ElevationB_decode_oer;
oer_type_encoder_f ElevationB_encode_oer;
per_type_decoder_f ElevationB_decode_uper;
per_type_encoder_f ElevationB_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ElevationB_H_ */
#include <asn_internal.h>
