/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_EventInfo_H_
#define	_EventInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TemporaryID.h"
#include "DDateTime.h"
#include "CauseCode.h"
#include "SubCauseCode.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MsgSegmentInfo;
struct DDateTime;
struct EventRecurrence;

/* EventInfo */
typedef struct EventInfo {
	TemporaryID_t	 eventID;
	struct MsgSegmentInfo	*msgSegmentInfo	/* OPTIONAL */;
	DDateTime_t	 startDateTime;
	struct DDateTime	*endDateTime	/* OPTIONAL */;
	struct EventInfo__eventRecurrence {
		A_SEQUENCE_OF(struct EventRecurrence) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *eventRecurrence;
	CauseCode_t	 causeCode;
	SubCauseCode_t	*subCauseCode	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_EventInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_EventInfo_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MsgSegmentInfo.h"
#include "DDateTime.h"
#include "EventRecurrence.h"

#endif	/* _EventInfo_H_ */
#include <asn_internal.h>
