/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "EventInfo.h"

static int
memb_eventRecurrence_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 5)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_eventRecurrence_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_eventRecurrence_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  1,  5 }	/* (SIZE(1..5,...)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_eventRecurrence_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_eventRecurrence_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  1,  5 }	/* (SIZE(1..5,...)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_eventRecurrence_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EventRecurrence,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_eventRecurrence_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventRecurrence_specs_6 = {
	sizeof(struct EventInfo__eventRecurrence),
	offsetof(struct EventInfo__eventRecurrence, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventRecurrence_6 = {
	"eventRecurrence",
	"eventRecurrence",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_eventRecurrence_tags_6,
	sizeof(asn_DEF_eventRecurrence_tags_6)
		/sizeof(asn_DEF_eventRecurrence_tags_6[0]) - 1, /* 1 */
	asn_DEF_eventRecurrence_tags_6,	/* Same as above */
	sizeof(asn_DEF_eventRecurrence_tags_6)
		/sizeof(asn_DEF_eventRecurrence_tags_6[0]), /* 2 */
	{ &asn_OER_type_eventRecurrence_constr_6, &asn_PER_type_eventRecurrence_constr_6, SEQUENCE_OF_constraint },
	asn_MBR_eventRecurrence_6,
	1,	/* Single element */
	&asn_SPC_eventRecurrence_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EventInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventInfo, eventID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventID"
		},
	{ ATF_POINTER, 1, offsetof(struct EventInfo, msgSegmentInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgSegmentInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"msgSegmentInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventInfo, startDateTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDateTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"startDateTime"
		},
	{ ATF_POINTER, 2, offsetof(struct EventInfo, endDateTime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDateTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"endDateTime"
		},
	{ ATF_POINTER, 1, offsetof(struct EventInfo, eventRecurrence),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_eventRecurrence_6,
		0,
		{ &asn_OER_memb_eventRecurrence_constr_6, &asn_PER_memb_eventRecurrence_constr_6,  memb_eventRecurrence_constraint_1 },
		0, 0, /* No default value */
		"eventRecurrence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventInfo, causeCode),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CauseCode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"causeCode"
		},
	{ ATF_POINTER, 1, offsetof(struct EventInfo, subCauseCode),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubCauseCode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subCauseCode"
		},
};
static const int asn_MAP_EventInfo_oms_1[] = { 1, 3, 4, 6 };
static const ber_tlv_tag_t asn_DEF_EventInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EventInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventIDat 36 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* msgSegmentInfoat 37 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* startDateTimeat 38 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* endDateTimeat 39 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* eventRecurrenceat 43 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* causeCodeat 44 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* subCauseCodeat 45 */
};
asn_SEQUENCE_specifics_t asn_SPC_EventInfo_specs_1 = {
	sizeof(struct EventInfo),
	offsetof(struct EventInfo, _asn_ctx),
	asn_MAP_EventInfo_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_EventInfo_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EventInfo = {
	"EventInfo",
	"EventInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_EventInfo_tags_1,
	sizeof(asn_DEF_EventInfo_tags_1)
		/sizeof(asn_DEF_EventInfo_tags_1[0]), /* 1 */
	asn_DEF_EventInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_EventInfo_tags_1)
		/sizeof(asn_DEF_EventInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EventInfo_1,
	7,	/* Elements count */
	&asn_SPC_EventInfo_specs_1	/* Additional specs */
};

