/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNAL-APPROACH-SUPPLEMENTAL-INFORMATION-REGION"
 * 	found in "CAMP/SPAT_TOSCo_Regional_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_GreenWindowInformation_H_
#define	_GreenWindowInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeMark.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GreenWindowInformation */
typedef struct GreenWindowInformation {
	TimeMark_t	 greenWindowStart;
	TimeMark_t	 greenWindowEnd;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GreenWindowInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GreenWindowInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_GreenWindowInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_GreenWindowInformation_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GreenWindowInformation_H_ */
#include <asn_internal.h>
