/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNAL-APPROACH-SUPPLEMENTAL-INFORMATION-REGION"
 * 	found in "CAMP/SPAT_TOSCo_Regional_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "GreenWindowInformation.h"

asn_TYPE_member_t asn_MBR_GreenWindowInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GreenWindowInformation, greenWindowStart),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"greenWindowStart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GreenWindowInformation, greenWindowEnd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"greenWindowEnd"
		},
};
static const ber_tlv_tag_t asn_DEF_GreenWindowInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GreenWindowInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* greenWindowStartat 8 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* greenWindowEndat 9 */
};
asn_SEQUENCE_specifics_t asn_SPC_GreenWindowInformation_specs_1 = {
	sizeof(struct GreenWindowInformation),
	offsetof(struct GreenWindowInformation, _asn_ctx),
	asn_MAP_GreenWindowInformation_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GreenWindowInformation = {
	"GreenWindowInformation",
	"GreenWindowInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_GreenWindowInformation_tags_1,
	sizeof(asn_DEF_GreenWindowInformation_tags_1)
		/sizeof(asn_DEF_GreenWindowInformation_tags_1[0]), /* 1 */
	asn_DEF_GreenWindowInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_GreenWindowInformation_tags_1)
		/sizeof(asn_DEF_GreenWindowInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GreenWindowInformation_1,
	2,	/* Elements count */
	&asn_SPC_GreenWindowInformation_specs_1	/* Additional specs */
};

