/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "IncidentsContainer.h"

static int
memb_description_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 513 && value <= 531)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_responderType_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 5)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_responderType_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..5)) */};
static asn_per_constraints_t asn_PER_type_responderType_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  5 }	/* (SIZE(1..5)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_description_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (513..531) */,
	-1};
static asn_per_constraints_t asn_PER_memb_description_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  513,  531 }	/* (513..531) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_responderType_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..5)) */};
static asn_per_constraints_t asn_PER_memb_responderType_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  5 }	/* (SIZE(1..5)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_responderType_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ResponderGroupAffected,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_responderType_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_responderType_specs_3 = {
	sizeof(struct IncidentsContainer__responderType),
	offsetof(struct IncidentsContainer__responderType, _asn_ctx),
	1,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_responderType_3 = {
	"responderType",
	"responderType",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_responderType_tags_3,
	sizeof(asn_DEF_responderType_tags_3)
		/sizeof(asn_DEF_responderType_tags_3[0]) - 1, /* 1 */
	asn_DEF_responderType_tags_3,	/* Same as above */
	sizeof(asn_DEF_responderType_tags_3)
		/sizeof(asn_DEF_responderType_tags_3[0]), /* 2 */
	{ &asn_OER_type_responderType_constr_3, &asn_PER_type_responderType_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_responderType_3,
	1,	/* Single element */
	&asn_SPC_responderType_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_IncidentsContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IncidentsContainer, description),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodes,
		0,
		{ &asn_OER_memb_description_constr_2, &asn_PER_memb_description_constr_2,  memb_description_constraint_1 },
		0, 0, /* No default value */
		"description"
		},
	{ ATF_POINTER, 4, offsetof(struct IncidentsContainer, responderType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_responderType_3,
		0,
		{ &asn_OER_memb_responderType_constr_3, &asn_PER_memb_responderType_constr_3,  memb_responderType_constraint_1 },
		0, 0, /* No default value */
		"responderType"
		},
	{ ATF_POINTER, 3, offsetof(struct IncidentsContainer, affectedLanes),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"affectedLanes"
		},
	{ ATF_POINTER, 2, offsetof(struct IncidentsContainer, advisorySpeed),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdvisorySpeed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"advisorySpeed"
		},
	{ ATF_POINTER, 1, offsetof(struct IncidentsContainer, congestionInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CongestionInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"congestionInfo"
		},
};
static const int asn_MAP_IncidentsContainer_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_IncidentsContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IncidentsContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* descriptionat 384 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* responderTypeat 386 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* affectedLanesat 387 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* advisorySpeedat 388 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* congestionInfoat 389 */
};
asn_SEQUENCE_specifics_t asn_SPC_IncidentsContainer_specs_1 = {
	sizeof(struct IncidentsContainer),
	offsetof(struct IncidentsContainer, _asn_ctx),
	asn_MAP_IncidentsContainer_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_IncidentsContainer_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IncidentsContainer = {
	"IncidentsContainer",
	"IncidentsContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_IncidentsContainer_tags_1,
	sizeof(asn_DEF_IncidentsContainer_tags_1)
		/sizeof(asn_DEF_IncidentsContainer_tags_1[0]), /* 1 */
	asn_DEF_IncidentsContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_IncidentsContainer_tags_1)
		/sizeof(asn_DEF_IncidentsContainer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IncidentsContainer_1,
	5,	/* Elements count */
	&asn_SPC_IncidentsContainer_specs_1	/* Additional specs */
};

