/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_IncidentsContainer_H_
#define	_IncidentsContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ITIScodes.h"
#include "ResponderGroupAffected.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionInfo;
struct AdvisorySpeed;
struct CongestionInfo;

/* IncidentsContainer */
typedef struct IncidentsContainer {
	ITIScodes_t	 description;
	struct IncidentsContainer__responderType {
		A_SEQUENCE_OF(ResponderGroupAffected_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *responderType;
	struct RegionInfo	*affectedLanes	/* OPTIONAL */;
	struct AdvisorySpeed	*advisorySpeed	/* OPTIONAL */;
	struct CongestionInfo	*congestionInfo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IncidentsContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IncidentsContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_IncidentsContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_IncidentsContainer_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionInfo.h"
#include "AdvisorySpeed.h"
#include "CongestionInfo.h"

#endif	/* _IncidentsContainer_H_ */
#include <asn_internal.h>
