/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_LaneGeometry_H_
#define	_LaneGeometry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneID.h"
#include "NodeSetLLE.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneGeometry_PR {
	LaneGeometry_PR_NOTHING,	/* No components present */
	LaneGeometry_PR_referenceLane,
	LaneGeometry_PR_nodeSet
	/* Extensions may appear below */
	
} LaneGeometry_PR;

/* LaneGeometry */
typedef struct LaneGeometry {
	LaneGeometry_PR present;
	union LaneGeometry_u {
		LaneID_t	 referenceLane;
		NodeSetLLE_t	 nodeSet;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneGeometry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneGeometry;
extern asn_CHOICE_specifics_t asn_SPC_LaneGeometry_specs_1;
extern asn_TYPE_member_t asn_MBR_LaneGeometry_1[2];
extern asn_per_constraints_t asn_PER_type_LaneGeometry_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneGeometry_H_ */
#include <asn_internal.h>
