/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_LatOffset_H_
#define	_LatOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LatOffset */
typedef long	 LatOffset_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LatOffset_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LatOffset;
asn_struct_free_f LatOffset_free;
asn_struct_print_f LatOffset_print;
asn_constr_check_f LatOffset_constraint;
ber_type_decoder_f LatOffset_decode_ber;
der_type_encoder_f LatOffset_encode_der;
xer_type_decoder_f LatOffset_decode_xer;
xer_type_encoder_f LatOffset_encode_xer;
oer_type_decoder_f LatOffset_decode_oer;
oer_type_encoder_f LatOffset_encode_oer;
per_type_decoder_f LatOffset_decode_uper;
per_type_encoder_f LatOffset_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LatOffset_H_ */
#include <asn_internal.h>
