/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_LongitudinalControlExtension_H_
#define	_LongitudinalControlExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LongitudinalControlState.h"
#include "TemporaryID.h"
#include "Acceleration.h"
#include "TimeConstant.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Tosco;

/* LongitudinalControlExtension */
typedef struct LongitudinalControlExtension {
	LongitudinalControlState_t	 state;
	TemporaryID_t	*targetID	/* OPTIONAL */;
	Acceleration_t	*accelForecast	/* OPTIONAL */;
	TimeConstant_t	*tau	/* OPTIONAL */;
	struct Tosco	*tosco	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LongitudinalControlExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LongitudinalControlExtension;
extern asn_SEQUENCE_specifics_t asn_SPC_LongitudinalControlExtension_specs_1;
extern asn_TYPE_member_t asn_MBR_LongitudinalControlExtension_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Tosco.h"

#endif	/* _LongitudinalControlExtension_H_ */
#include <asn_internal.h>
