/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "LongitudinalControlExtension.h"

asn_TYPE_member_t asn_MBR_LongitudinalControlExtension_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LongitudinalControlExtension, state),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LongitudinalControlState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"state"
		},
	{ ATF_POINTER, 4, offsetof(struct LongitudinalControlExtension, targetID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetID"
		},
	{ ATF_POINTER, 3, offsetof(struct LongitudinalControlExtension, accelForecast),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Acceleration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"accelForecast"
		},
	{ ATF_POINTER, 2, offsetof(struct LongitudinalControlExtension, tau),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeConstant,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tau"
		},
	{ ATF_POINTER, 1, offsetof(struct LongitudinalControlExtension, tosco),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Tosco,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tosco"
		},
};
static const int asn_MAP_LongitudinalControlExtension_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_LongitudinalControlExtension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LongitudinalControlExtension_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* stateat 11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* targetIDat 12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* accelForecastat 13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* tauat 14 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* toscoat 15 */
};
asn_SEQUENCE_specifics_t asn_SPC_LongitudinalControlExtension_specs_1 = {
	sizeof(struct LongitudinalControlExtension),
	offsetof(struct LongitudinalControlExtension, _asn_ctx),
	asn_MAP_LongitudinalControlExtension_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_LongitudinalControlExtension_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LongitudinalControlExtension = {
	"LongitudinalControlExtension",
	"LongitudinalControlExtension",
	&asn_OP_SEQUENCE,
	asn_DEF_LongitudinalControlExtension_tags_1,
	sizeof(asn_DEF_LongitudinalControlExtension_tags_1)
		/sizeof(asn_DEF_LongitudinalControlExtension_tags_1[0]), /* 1 */
	asn_DEF_LongitudinalControlExtension_tags_1,	/* Same as above */
	sizeof(asn_DEF_LongitudinalControlExtension_tags_1)
		/sizeof(asn_DEF_LongitudinalControlExtension_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LongitudinalControlExtension_1,
	5,	/* Elements count */
	&asn_SPC_LongitudinalControlExtension_specs_1	/* Additional specs */
};

