/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_LongitudinalControlState_H_
#define	_LongitudinalControlState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LongitudinalControlState {
	LongitudinalControlState_manual	= 0,
	LongitudinalControlState_cc	= 1,
	LongitudinalControlState_acc	= 2,
	LongitudinalControlState_cacc_one	= 3,
	LongitudinalControlState_cacc_multi	= 4,
	LongitudinalControlState_sensor_auto	= 5,
	LongitudinalControlState_fused_auto	= 6,
	LongitudinalControlState_manual_over	= 7
	/*
	 * Enumeration is extensible
	 */
} e_LongitudinalControlState;

/* LongitudinalControlState */
typedef long	 LongitudinalControlState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LongitudinalControlState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LongitudinalControlState;
extern const asn_INTEGER_specifics_t asn_SPC_LongitudinalControlState_specs_1;
asn_struct_free_f LongitudinalControlState_free;
asn_struct_print_f LongitudinalControlState_print;
asn_constr_check_f LongitudinalControlState_constraint;
ber_type_decoder_f LongitudinalControlState_decode_ber;
der_type_encoder_f LongitudinalControlState_encode_der;
xer_type_decoder_f LongitudinalControlState_decode_xer;
xer_type_encoder_f LongitudinalControlState_encode_xer;
oer_type_decoder_f LongitudinalControlState_decode_oer;
oer_type_encoder_f LongitudinalControlState_encode_oer;
per_type_decoder_f LongitudinalControlState_decode_uper;
per_type_encoder_f LongitudinalControlState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LongitudinalControlState_H_ */
#include <asn_internal.h>
