/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "LONGITUDINAL-CONTROL-TESTING-REGION_BasicSafetyMessage-regExt.h"

/*
 * This type is implemented using LongitudinalControlExtension,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt = {
	"BasicSafetyMessage-regExt",
	"BasicSafetyMessage-regExt",
	&asn_OP_SEQUENCE,
	asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_tags_1,
	sizeof(asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_tags_1)
		/sizeof(asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_tags_1[0]), /* 1 */
	asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_tags_1,	/* Same as above */
	sizeof(asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_tags_1)
		/sizeof(asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LongitudinalControlExtension_1,
	5,	/* Elements count */
	&asn_SPC_LongitudinalControlExtension_specs_1	/* Additional specs */
};

