/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "LongitudinalControlState.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_LongitudinalControlState_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_LongitudinalControlState_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  7 }	/* (0..7,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_LongitudinalControlState_value2enum_1[] = {
	{ 0,	6,	"manual" },
	{ 1,	2,	"cc" },
	{ 2,	3,	"acc" },
	{ 3,	8,	"cacc-one" },
	{ 4,	10,	"cacc-multi" },
	{ 5,	11,	"sensor-auto" },
	{ 6,	10,	"fused-auto" },
	{ 7,	11,	"manual-over" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_LongitudinalControlState_enum2value_1[] = {
	2,	/* acc(2) */
	4,	/* cacc-multi(4) */
	3,	/* cacc-one(3) */
	1,	/* cc(1) */
	6,	/* fused-auto(6) */
	0,	/* manual(0) */
	7,	/* manual-over(7) */
	5	/* sensor-auto(5) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_LongitudinalControlState_specs_1 = {
	asn_MAP_LongitudinalControlState_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_LongitudinalControlState_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	9,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_LongitudinalControlState_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_LongitudinalControlState = {
	"LongitudinalControlState",
	"LongitudinalControlState",
	&asn_OP_NativeEnumerated,
	asn_DEF_LongitudinalControlState_tags_1,
	sizeof(asn_DEF_LongitudinalControlState_tags_1)
		/sizeof(asn_DEF_LongitudinalControlState_tags_1[0]), /* 1 */
	asn_DEF_LongitudinalControlState_tags_1,	/* Same as above */
	sizeof(asn_DEF_LongitudinalControlState_tags_1)
		/sizeof(asn_DEF_LongitudinalControlState_tags_1[0]), /* 1 */
	{ &asn_OER_type_LongitudinalControlState_constr_1, &asn_PER_type_LongitudinalControlState_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_LongitudinalControlState_specs_1	/* Additional specs */
};

