/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_H_
#define	_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LongitudinalControlExtension.h"

#ifdef __cplusplus
extern "C" {
#endif

/* BasicSafetyMessage-regExt */
typedef LongitudinalControlExtension_t	 LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt;
asn_struct_free_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_free;
asn_struct_print_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_print;
asn_constr_check_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_constraint;
ber_type_decoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_decode_ber;
der_type_encoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_encode_der;
xer_type_decoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_decode_xer;
xer_type_encoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_encode_xer;
oer_type_decoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_decode_oer;
oer_type_encoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_encode_oer;
per_type_decoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_decode_uper;
per_type_encoder_f LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LONGITUDINAL_CONTROL_TESTING_REGION_BasicSafetyMessage_regExt_H_ */
#include <asn_internal.h>
