/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "ManyDayOfWeek.h"

static asn_oer_constraints_t asn_OER_type_ManyDayOfWeek_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_type_ManyDayOfWeek_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ManyDayOfWeek_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_DayOfWeek,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ManyDayOfWeek_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ManyDayOfWeek_specs_1 = {
	sizeof(struct ManyDayOfWeek),
	offsetof(struct ManyDayOfWeek, _asn_ctx),
	1,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_ManyDayOfWeek = {
	"ManyDayOfWeek",
	"ManyDayOfWeek",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ManyDayOfWeek_tags_1,
	sizeof(asn_DEF_ManyDayOfWeek_tags_1)
		/sizeof(asn_DEF_ManyDayOfWeek_tags_1[0]), /* 1 */
	asn_DEF_ManyDayOfWeek_tags_1,	/* Same as above */
	sizeof(asn_DEF_ManyDayOfWeek_tags_1)
		/sizeof(asn_DEF_ManyDayOfWeek_tags_1[0]), /* 1 */
	{ &asn_OER_type_ManyDayOfWeek_constr_1, &asn_PER_type_ManyDayOfWeek_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_ManyDayOfWeek_1,
	1,	/* Single element */
	&asn_SPC_ManyDayOfWeek_specs_1	/* Additional specs */
};

