/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_ManyDayOfWeek_H_
#define	_ManyDayOfWeek_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DayOfWeek.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ManyDayOfWeek */
typedef struct ManyDayOfWeek {
	A_SEQUENCE_OF(DayOfWeek_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManyDayOfWeek_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManyDayOfWeek;

#ifdef __cplusplus
}
#endif

#endif	/* _ManyDayOfWeek_H_ */
#include <asn_internal.h>
