/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_Material_H_
#define	_Material_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Material {
	Material_asphalt	= 0,
	Material_concrete	= 1,
	Material_gravel	= 2,
	Material_brushedConcrete	= 3
	/*
	 * Enumeration is extensible
	 */
} e_Material;

/* Material */
typedef long	 Material_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Material_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Material;
extern const asn_INTEGER_specifics_t asn_SPC_Material_specs_1;
asn_struct_free_f Material_free;
asn_struct_print_f Material_print;
asn_constr_check_f Material_constraint;
ber_type_decoder_f Material_decode_ber;
der_type_encoder_f Material_encode_der;
xer_type_decoder_f Material_decode_xer;
xer_type_encoder_f Material_encode_xer;
oer_type_decoder_f Material_decode_oer;
oer_type_encoder_f Material_encode_oer;
per_type_decoder_f Material_decode_uper;
per_type_encoder_f Material_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Material_H_ */
#include <asn_internal.h>
