/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "J2735_201603DA-CAMP.ASN"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_MsgCountB_H_
#define	_MsgCountB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MsgCountB */
typedef long	 MsgCountB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgCountB;
asn_struct_free_f MsgCountB_free;
asn_struct_print_f MsgCountB_print;
asn_constr_check_f MsgCountB_constraint;
ber_type_decoder_f MsgCountB_decode_ber;
der_type_encoder_f MsgCountB_encode_der;
xer_type_decoder_f MsgCountB_decode_xer;
xer_type_encoder_f MsgCountB_encode_xer;
oer_type_decoder_f MsgCountB_decode_oer;
oer_type_encoder_f MsgCountB_encode_oer;
per_type_decoder_f MsgCountB_decode_uper;
per_type_encoder_f MsgCountB_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgCountB_H_ */
#include <asn_internal.h>
