/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_MsgSegmentInfo_H_
#define	_MsgSegmentInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SegmentCount.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MsgSegmentInfo */
typedef struct MsgSegmentInfo {
	SegmentCount_t	 totalMsgSegments;
	SegmentCount_t	 thisSegmentNum;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MsgSegmentInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgSegmentInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_MsgSegmentInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_MsgSegmentInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MsgSegmentInfo_H_ */
#include <asn_internal.h>
