/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_NodeLLE_H_
#define	_NodeLLE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NodePointLLE.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeAttributeSetLLE;

/* NodeLLE */
typedef struct NodeLLE {
	NodePointLLE_t	 nodePoint;
	struct NodeAttributeSetLLE	*nodeAttributes	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeLLE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeLLE;
extern asn_SEQUENCE_specifics_t asn_SPC_NodeLLE_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeLLE_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeAttributeSetLLE.h"

#endif	/* _NodeLLE_H_ */
#include <asn_internal.h>
