/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_NodeAttributeSetLLE_H_
#define	_NodeAttributeSetLLE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneWidth.h"
#include "TaperLeft.h"
#include "TaperRight.h"
#include "LaneClosed.h"
#include "PeoplePresent.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RSMSpeedLimit;

/* NodeAttributeSetLLE */
typedef struct NodeAttributeSetLLE {
	struct RSMSpeedLimit	*speedLimit	/* OPTIONAL */;
	LaneWidth_t	*width	/* OPTIONAL */;
	TaperLeft_t	*taperLeft	/* OPTIONAL */;
	TaperRight_t	*taperRight	/* OPTIONAL */;
	LaneClosed_t	*laneClosed	/* OPTIONAL */;
	PeoplePresent_t	*peoplePresent	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeAttributeSetLLE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeAttributeSetLLE;
extern asn_SEQUENCE_specifics_t asn_SPC_NodeAttributeSetLLE_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeAttributeSetLLE_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RSMSpeedLimit.h"

#endif	/* _NodeAttributeSetLLE_H_ */
#include <asn_internal.h>
