/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "NodeAttributeSetLLE.h"

asn_TYPE_member_t asn_MBR_NodeAttributeSetLLE_1[] = {
	{ ATF_POINTER, 6, offsetof(struct NodeAttributeSetLLE, speedLimit),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSMSpeedLimit,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speedLimit"
		},
	{ ATF_POINTER, 5, offsetof(struct NodeAttributeSetLLE, width),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneWidth,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"width"
		},
	{ ATF_POINTER, 4, offsetof(struct NodeAttributeSetLLE, taperLeft),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TaperLeft,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"taperLeft"
		},
	{ ATF_POINTER, 3, offsetof(struct NodeAttributeSetLLE, taperRight),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TaperRight,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"taperRight"
		},
	{ ATF_POINTER, 2, offsetof(struct NodeAttributeSetLLE, laneClosed),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneClosed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneClosed"
		},
	{ ATF_POINTER, 1, offsetof(struct NodeAttributeSetLLE, peoplePresent),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PeoplePresent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"peoplePresent"
		},
};
static const int asn_MAP_NodeAttributeSetLLE_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_NodeAttributeSetLLE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NodeAttributeSetLLE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* speedLimitat 204 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* widthat 205 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* taperLeftat 206 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* taperRightat 207 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* laneClosedat 208 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* peoplePresentat 209 */
};
asn_SEQUENCE_specifics_t asn_SPC_NodeAttributeSetLLE_specs_1 = {
	sizeof(struct NodeAttributeSetLLE),
	offsetof(struct NodeAttributeSetLLE, _asn_ctx),
	asn_MAP_NodeAttributeSetLLE_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_NodeAttributeSetLLE_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NodeAttributeSetLLE = {
	"NodeAttributeSetLLE",
	"NodeAttributeSetLLE",
	&asn_OP_SEQUENCE,
	asn_DEF_NodeAttributeSetLLE_tags_1,
	sizeof(asn_DEF_NodeAttributeSetLLE_tags_1)
		/sizeof(asn_DEF_NodeAttributeSetLLE_tags_1[0]), /* 1 */
	asn_DEF_NodeAttributeSetLLE_tags_1,	/* Same as above */
	sizeof(asn_DEF_NodeAttributeSetLLE_tags_1)
		/sizeof(asn_DEF_NodeAttributeSetLLE_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NodeAttributeSetLLE_1,
	6,	/* Elements count */
	&asn_SPC_NodeAttributeSetLLE_specs_1	/* Additional specs */
};

