/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "NodeLLE.h"

asn_TYPE_member_t asn_MBR_NodeLLE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NodeLLE, nodePoint),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NodePointLLE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nodePoint"
		},
	{ ATF_POINTER, 1, offsetof(struct NodeLLE, nodeAttributes),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeAttributeSetLLE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nodeAttributes"
		},
};
static const int asn_MAP_NodeLLE_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_NodeLLE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NodeLLE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nodePointat 170 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nodeAttributesat 171 */
};
asn_SEQUENCE_specifics_t asn_SPC_NodeLLE_specs_1 = {
	sizeof(struct NodeLLE),
	offsetof(struct NodeLLE, _asn_ctx),
	asn_MAP_NodeLLE_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_NodeLLE_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NodeLLE = {
	"NodeLLE",
	"NodeLLE",
	&asn_OP_SEQUENCE,
	asn_DEF_NodeLLE_tags_1,
	sizeof(asn_DEF_NodeLLE_tags_1)
		/sizeof(asn_DEF_NodeLLE_tags_1[0]), /* 1 */
	asn_DEF_NodeLLE_tags_1,	/* Same as above */
	sizeof(asn_DEF_NodeLLE_tags_1)
		/sizeof(asn_DEF_NodeLLE_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NodeLLE_1,
	2,	/* Elements count */
	&asn_SPC_NodeLLE_specs_1	/* Additional specs */
};

