/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "NodePointLLE.h"

static asn_oer_constraints_t asn_OER_type_NodePointLLE_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_NodePointLLE_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_NodePointLLE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NodePointLLE, choice.node_3Dabsolute),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position3D,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"node-3Dabsolute"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NodePointLLE, choice.node_3Doffset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset3D,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"node-3Doffset"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_NodePointLLE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* node-3Dabsoluteat 178 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* node-3Doffsetat 179 */
};
asn_CHOICE_specifics_t asn_SPC_NodePointLLE_specs_1 = {
	sizeof(struct NodePointLLE),
	offsetof(struct NodePointLLE, _asn_ctx),
	offsetof(struct NodePointLLE, present),
	sizeof(((struct NodePointLLE *)0)->present),
	asn_MAP_NodePointLLE_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_NodePointLLE = {
	"NodePointLLE",
	"NodePointLLE",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_NodePointLLE_constr_1, &asn_PER_type_NodePointLLE_constr_1, CHOICE_constraint },
	asn_MBR_NodePointLLE_1,
	2,	/* Elements count */
	&asn_SPC_NodePointLLE_specs_1	/* Additional specs */
};

