/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "Obstructions.h"

static int
memb_description_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1282 && value <= 1319)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_location_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 7937 && value <= 8030)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_description_constr_4 CC_NOTUSED = {
	{ 2, 1 }	/* (1282..1319) */,
	-1};
static asn_per_constraints_t asn_PER_memb_description_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  1282,  1319 }	/* (1282..1319) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_location_constr_5 CC_NOTUSED = {
	{ 2, 1 }	/* (7937..8030) */,
	-1};
static asn_per_constraints_t asn_PER_memb_location_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  7937,  8030 }	/* (7937..8030) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Obstructions_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Obstructions, detection),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObstacleDetection,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"detection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Obstructions, roadSegmentID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoadSegmentReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"roadSegmentID"
		},
	{ ATF_POINTER, 5, offsetof(struct Obstructions, description),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodes,
		0,
		{ &asn_OER_memb_description_constr_4, &asn_PER_memb_description_constr_4,  memb_description_constraint_1 },
		0, 0, /* No default value */
		"description"
		},
	{ ATF_POINTER, 4, offsetof(struct Obstructions, location),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodes,
		0,
		{ &asn_OER_memb_location_constr_5, &asn_PER_memb_location_constr_5,  memb_location_constraint_1 },
		0, 0, /* No default value */
		"location"
		},
	{ ATF_POINTER, 3, offsetof(struct Obstructions, affectedLanes),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"affectedLanes"
		},
	{ ATF_POINTER, 2, offsetof(struct Obstructions, reducedspeed),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdvisorySpeed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedspeed"
		},
	{ ATF_POINTER, 1, offsetof(struct Obstructions, affectedvehicles),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DisabledVehicle,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"affectedvehicles"
		},
};
static const int asn_MAP_Obstructions_oms_1[] = { 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_Obstructions_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Obstructions_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* detectionat 413 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* roadSegmentIDat 414 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* descriptionat 415 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* locationat 416 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* affectedLanesat 417 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* reducedspeedat 418 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* affectedvehiclesat 419 */
};
asn_SEQUENCE_specifics_t asn_SPC_Obstructions_specs_1 = {
	sizeof(struct Obstructions),
	offsetof(struct Obstructions, _asn_ctx),
	asn_MAP_Obstructions_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_Obstructions_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Obstructions = {
	"Obstructions",
	"Obstructions",
	&asn_OP_SEQUENCE,
	asn_DEF_Obstructions_tags_1,
	sizeof(asn_DEF_Obstructions_tags_1)
		/sizeof(asn_DEF_Obstructions_tags_1[0]), /* 1 */
	asn_DEF_Obstructions_tags_1,	/* Same as above */
	sizeof(asn_DEF_Obstructions_tags_1)
		/sizeof(asn_DEF_Obstructions_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Obstructions_1,
	7,	/* Elements count */
	&asn_SPC_Obstructions_specs_1	/* Additional specs */
};

