/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_Obstructions_H_
#define	_Obstructions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObstacleDetection.h"
#include "RoadSegmentReferenceID.h"
#include "ITIScodes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionInfo;
struct AdvisorySpeed;
struct DisabledVehicle;

/* Obstructions */
typedef struct Obstructions {
	ObstacleDetection_t	 detection;
	RoadSegmentReferenceID_t	 roadSegmentID;
	ITIScodes_t	*description	/* OPTIONAL */;
	ITIScodes_t	*location	/* OPTIONAL */;
	struct RegionInfo	*affectedLanes	/* OPTIONAL */;
	struct AdvisorySpeed	*reducedspeed	/* OPTIONAL */;
	struct DisabledVehicle	*affectedvehicles	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Obstructions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Obstructions;
extern asn_SEQUENCE_specifics_t asn_SPC_Obstructions_specs_1;
extern asn_TYPE_member_t asn_MBR_Obstructions_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionInfo.h"
#include "AdvisorySpeed.h"
#include "DisabledVehicle.h"

#endif	/* _Obstructions_H_ */
#include <asn_internal.h>
