/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "Offset3D.h"

asn_TYPE_member_t asn_MBR_Offset3D_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Offset3D, lat_offset),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LatOffset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lat-offset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Offset3D, long_offset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LongOffset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"long-offset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Offset3D, elev_offset),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ElevOffset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"elev-offset"
		},
};
static const ber_tlv_tag_t asn_DEF_Offset3D_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Offset3D_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lat-offsetat 185 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* long-offsetat 186 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* elev-offsetat 187 */
};
asn_SEQUENCE_specifics_t asn_SPC_Offset3D_specs_1 = {
	sizeof(struct Offset3D),
	offsetof(struct Offset3D, _asn_ctx),
	asn_MAP_Offset3D_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Offset3D = {
	"Offset3D",
	"Offset3D",
	&asn_OP_SEQUENCE,
	asn_DEF_Offset3D_tags_1,
	sizeof(asn_DEF_Offset3D_tags_1)
		/sizeof(asn_DEF_Offset3D_tags_1[0]), /* 1 */
	asn_DEF_Offset3D_tags_1,	/* Same as above */
	sizeof(asn_DEF_Offset3D_tags_1)
		/sizeof(asn_DEF_Offset3D_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Offset3D_1,
	3,	/* Elements count */
	&asn_SPC_Offset3D_specs_1	/* Additional specs */
};

