/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_Offset3D_H_
#define	_Offset3D_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LatOffset.h"
#include "LongOffset.h"
#include "ElevOffset.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Offset3D */
typedef struct Offset3D {
	LatOffset_t	 lat_offset;
	LongOffset_t	 long_offset;
	ElevOffset_t	 elev_offset;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Offset3D_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Offset3D;
extern asn_SEQUENCE_specifics_t asn_SPC_Offset3D_specs_1;
extern asn_TYPE_member_t asn_MBR_Offset3D_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Offset3D_H_ */
#include <asn_internal.h>
