/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "OverheightVehicle.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_heightViolation_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_heightViolation_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_heightViolation_value2enum_7[] = {
	{ 0,	16,	"not-in-violation" },
	{ 1,	12,	"in-violation" },
	{ 2,	15,	"less-than-15-cm" },
	{ 3,	7,	"unknown" }
};
static const unsigned int asn_MAP_heightViolation_enum2value_7[] = {
	1,	/* in-violation(1) */
	2,	/* less-than-15-cm(2) */
	0,	/* not-in-violation(0) */
	3	/* unknown(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_heightViolation_specs_7 = {
	asn_MAP_heightViolation_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_heightViolation_enum2value_7,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_heightViolation_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_heightViolation_7 = {
	"heightViolation",
	"heightViolation",
	&asn_OP_NativeEnumerated,
	asn_DEF_heightViolation_tags_7,
	sizeof(asn_DEF_heightViolation_tags_7)
		/sizeof(asn_DEF_heightViolation_tags_7[0]) - 1, /* 1 */
	asn_DEF_heightViolation_tags_7,	/* Same as above */
	sizeof(asn_DEF_heightViolation_tags_7)
		/sizeof(asn_DEF_heightViolation_tags_7[0]), /* 2 */
	{ &asn_OER_type_heightViolation_constr_7, &asn_PER_type_heightViolation_constr_7, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_heightViolation_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_OverheightVehicle_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OverheightVehicle, roadSegmentID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoadSegmentReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"roadSegmentID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OverheightVehicle, point),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position3D,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"point"
		},
	{ ATF_POINTER, 2, offsetof(struct OverheightVehicle, intersection),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntersectionReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"intersection"
		},
	{ ATF_POINTER, 1, offsetof(struct OverheightVehicle, vehicleHeight),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleHeight,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vehicleHeight"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OverheightVehicle, clearanceHeight),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleHeight,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"clearanceHeight"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OverheightVehicle, heightViolation),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_heightViolation_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"heightViolation"
		},
};
static const int asn_MAP_OverheightVehicle_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_OverheightVehicle_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OverheightVehicle_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* roadSegmentIDat 424 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pointat 425 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* intersectionat 426 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* vehicleHeightat 427 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* clearanceHeightat 428 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* heightViolationat 429 */
};
asn_SEQUENCE_specifics_t asn_SPC_OverheightVehicle_specs_1 = {
	sizeof(struct OverheightVehicle),
	offsetof(struct OverheightVehicle, _asn_ctx),
	asn_MAP_OverheightVehicle_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_OverheightVehicle_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OverheightVehicle = {
	"OverheightVehicle",
	"OverheightVehicle",
	&asn_OP_SEQUENCE,
	asn_DEF_OverheightVehicle_tags_1,
	sizeof(asn_DEF_OverheightVehicle_tags_1)
		/sizeof(asn_DEF_OverheightVehicle_tags_1[0]), /* 1 */
	asn_DEF_OverheightVehicle_tags_1,	/* Same as above */
	sizeof(asn_DEF_OverheightVehicle_tags_1)
		/sizeof(asn_DEF_OverheightVehicle_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_OverheightVehicle_1,
	6,	/* Elements count */
	&asn_SPC_OverheightVehicle_specs_1	/* Additional specs */
};

