/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_Path_H_
#define	_Path_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "PathPoints.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Path */
typedef struct Path {
	long	 pathWidth;
	PathPoints_t	 pathPoints;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Path_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Path;
extern asn_SEQUENCE_specifics_t asn_SPC_Path_specs_1;
extern asn_TYPE_member_t asn_MBR_Path_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Path_H_ */
#include <asn_internal.h>
