/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "RailCrossing.h"

static int
memb_durationDescription_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1537 && value <= 1543)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_durationDescription_constr_7 CC_NOTUSED = {
	{ 2, 1 }	/* (1537..1543) */,
	-1};
static asn_per_constraints_t asn_PER_memb_durationDescription_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1537,  1543 }	/* (1537..1543) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RailCrossing_1[] = {
	{ ATF_POINTER, 3, offsetof(struct RailCrossing, crossingSignalOn),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crossingSignalOn"
		},
	{ ATF_POINTER, 2, offsetof(struct RailCrossing, crossingGateDown),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crossingGateDown"
		},
	{ ATF_POINTER, 1, offsetof(struct RailCrossing, approachingTrain),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"approachingTrain"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RailCrossing, trainCrossingInProgress),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"trainCrossingInProgress"
		},
	{ ATF_POINTER, 2, offsetof(struct RailCrossing, durationTime),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MinutesDuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"durationTime"
		},
	{ ATF_POINTER, 1, offsetof(struct RailCrossing, durationDescription),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodes,
		0,
		{ &asn_OER_memb_durationDescription_constr_7, &asn_PER_memb_durationDescription_constr_7,  memb_durationDescription_constraint_1 },
		0, 0, /* No default value */
		"durationDescription"
		},
};
static const int asn_MAP_RailCrossing_oms_1[] = { 0, 1, 2, 4, 5 };
static const ber_tlv_tag_t asn_DEF_RailCrossing_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RailCrossing_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crossingSignalOnat 434 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* crossingGateDownat 435 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* approachingTrainat 436 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* trainCrossingInProgressat 437 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* durationTimeat 438 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* durationDescriptionat 439 */
};
asn_SEQUENCE_specifics_t asn_SPC_RailCrossing_specs_1 = {
	sizeof(struct RailCrossing),
	offsetof(struct RailCrossing, _asn_ctx),
	asn_MAP_RailCrossing_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_RailCrossing_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RailCrossing = {
	"RailCrossing",
	"RailCrossing",
	&asn_OP_SEQUENCE,
	asn_DEF_RailCrossing_tags_1,
	sizeof(asn_DEF_RailCrossing_tags_1)
		/sizeof(asn_DEF_RailCrossing_tags_1[0]), /* 1 */
	asn_DEF_RailCrossing_tags_1,	/* Same as above */
	sizeof(asn_DEF_RailCrossing_tags_1)
		/sizeof(asn_DEF_RailCrossing_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RailCrossing_1,
	6,	/* Elements count */
	&asn_SPC_RailCrossing_specs_1	/* Additional specs */
};

