/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_RailCrossing_H_
#define	_RailCrossing_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "MinutesDuration.h"
#include "ITIScodes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RailCrossing */
typedef struct RailCrossing {
	BOOLEAN_t	*crossingSignalOn	/* OPTIONAL */;
	BOOLEAN_t	*crossingGateDown	/* OPTIONAL */;
	BOOLEAN_t	*approachingTrain	/* OPTIONAL */;
	BOOLEAN_t	 trainCrossingInProgress;
	MinutesDuration_t	*durationTime	/* OPTIONAL */;
	ITIScodes_t	*durationDescription	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RailCrossing_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RailCrossing;
extern asn_SEQUENCE_specifics_t asn_SPC_RailCrossing_specs_1;
extern asn_TYPE_member_t asn_MBR_RailCrossing_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _RailCrossing_H_ */
#include <asn_internal.h>
