/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_ReducedSpeedZoneContainer_H_
#define	_ReducedSpeedZoneContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PeoplePresent.h"
#include "ITIScodes.h"
#include "PublicSafetyDirectingTrafficSubType.h"
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RSMSpeedLimit;
struct AreaType;
struct LaneInfo;

/* ReducedSpeedZoneContainer */
typedef struct ReducedSpeedZoneContainer {
	struct ReducedSpeedZoneContainer__laneStatus {
		A_SEQUENCE_OF(struct LaneInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laneStatus;
	PeoplePresent_t	*peoplePresent	/* OPTIONAL */;
	struct RSMSpeedLimit	*speedLimit	/* OPTIONAL */;
	ITIScodes_t	*roadClosureDescription	/* OPTIONAL */;
	ITIScodes_t	*roadWorkDescription	/* OPTIONAL */;
	PublicSafetyDirectingTrafficSubType_t	*flagman	/* OPTIONAL */;
	BOOLEAN_t	*trucksEnteringLeaving	/* OPTIONAL */;
	struct AreaType	*rszRegion	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReducedSpeedZoneContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReducedSpeedZoneContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ReducedSpeedZoneContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ReducedSpeedZoneContainer_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RSMSpeedLimit.h"
#include "AreaType.h"
#include "LaneInfo.h"

#endif	/* _ReducedSpeedZoneContainer_H_ */
#include <asn_internal.h>
