/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "ReducedSpeedZoneContainer.h"

static int
memb_laneStatus_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 10)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_roadClosureDescription_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 769 && value <= 895)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_roadWorkDescription_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1025 && value <= 1061)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_laneStatus_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_laneStatus_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  1,  10 }	/* (SIZE(1..10,...)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_laneStatus_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_laneStatus_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  1,  10 }	/* (SIZE(1..10,...)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_roadClosureDescription_constr_6 CC_NOTUSED = {
	{ 2, 1 }	/* (769..895) */,
	-1};
static asn_per_constraints_t asn_PER_memb_roadClosureDescription_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  769,  895 }	/* (769..895) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_roadWorkDescription_constr_7 CC_NOTUSED = {
	{ 2, 1 }	/* (1025..1061) */,
	-1};
static asn_per_constraints_t asn_PER_memb_roadWorkDescription_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  1025,  1061 }	/* (1025..1061) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_laneStatus_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LaneInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_laneStatus_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_laneStatus_specs_2 = {
	sizeof(struct ReducedSpeedZoneContainer__laneStatus),
	offsetof(struct ReducedSpeedZoneContainer__laneStatus, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_laneStatus_2 = {
	"laneStatus",
	"laneStatus",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_laneStatus_tags_2,
	sizeof(asn_DEF_laneStatus_tags_2)
		/sizeof(asn_DEF_laneStatus_tags_2[0]) - 1, /* 1 */
	asn_DEF_laneStatus_tags_2,	/* Same as above */
	sizeof(asn_DEF_laneStatus_tags_2)
		/sizeof(asn_DEF_laneStatus_tags_2[0]), /* 2 */
	{ &asn_OER_type_laneStatus_constr_2, &asn_PER_type_laneStatus_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_laneStatus_2,
	1,	/* Single element */
	&asn_SPC_laneStatus_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ReducedSpeedZoneContainer_1[] = {
	{ ATF_POINTER, 8, offsetof(struct ReducedSpeedZoneContainer, laneStatus),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_laneStatus_2,
		0,
		{ &asn_OER_memb_laneStatus_constr_2, &asn_PER_memb_laneStatus_constr_2,  memb_laneStatus_constraint_1 },
		0, 0, /* No default value */
		"laneStatus"
		},
	{ ATF_POINTER, 7, offsetof(struct ReducedSpeedZoneContainer, peoplePresent),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PeoplePresent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"peoplePresent"
		},
	{ ATF_POINTER, 6, offsetof(struct ReducedSpeedZoneContainer, speedLimit),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSMSpeedLimit,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speedLimit"
		},
	{ ATF_POINTER, 5, offsetof(struct ReducedSpeedZoneContainer, roadClosureDescription),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodes,
		0,
		{ &asn_OER_memb_roadClosureDescription_constr_6, &asn_PER_memb_roadClosureDescription_constr_6,  memb_roadClosureDescription_constraint_1 },
		0, 0, /* No default value */
		"roadClosureDescription"
		},
	{ ATF_POINTER, 4, offsetof(struct ReducedSpeedZoneContainer, roadWorkDescription),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodes,
		0,
		{ &asn_OER_memb_roadWorkDescription_constr_7, &asn_PER_memb_roadWorkDescription_constr_7,  memb_roadWorkDescription_constraint_1 },
		0, 0, /* No default value */
		"roadWorkDescription"
		},
	{ ATF_POINTER, 3, offsetof(struct ReducedSpeedZoneContainer, flagman),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PublicSafetyDirectingTrafficSubType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"flagman"
		},
	{ ATF_POINTER, 2, offsetof(struct ReducedSpeedZoneContainer, trucksEnteringLeaving),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"trucksEnteringLeaving"
		},
	{ ATF_POINTER, 1, offsetof(struct ReducedSpeedZoneContainer, rszRegion),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AreaType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rszRegion"
		},
};
static const int asn_MAP_ReducedSpeedZoneContainer_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_ReducedSpeedZoneContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReducedSpeedZoneContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* laneStatusat 103 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* peoplePresentat 104 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* speedLimitat 105 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* roadClosureDescriptionat 106 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* roadWorkDescriptionat 107 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* flagmanat 108 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* trucksEnteringLeavingat 109 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* rszRegionat 110 */
};
asn_SEQUENCE_specifics_t asn_SPC_ReducedSpeedZoneContainer_specs_1 = {
	sizeof(struct ReducedSpeedZoneContainer),
	offsetof(struct ReducedSpeedZoneContainer, _asn_ctx),
	asn_MAP_ReducedSpeedZoneContainer_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_ReducedSpeedZoneContainer_oms_1,	/* Optional members */
	8, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReducedSpeedZoneContainer = {
	"ReducedSpeedZoneContainer",
	"ReducedSpeedZoneContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ReducedSpeedZoneContainer_tags_1,
	sizeof(asn_DEF_ReducedSpeedZoneContainer_tags_1)
		/sizeof(asn_DEF_ReducedSpeedZoneContainer_tags_1[0]), /* 1 */
	asn_DEF_ReducedSpeedZoneContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReducedSpeedZoneContainer_tags_1)
		/sizeof(asn_DEF_ReducedSpeedZoneContainer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ReducedSpeedZoneContainer_1,
	8,	/* Elements count */
	&asn_SPC_ReducedSpeedZoneContainer_specs_1	/* Additional specs */
};

