/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_RegionInfo_H_
#define	_RegionInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ApplicableHeading.h"
#include "Position3D.h"
#include "ReferencePointType.h"
#include "DescriptiveName.h"
#include "EventLength.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RSMSpeedLimit;
struct AreaType;

/* RegionInfo */
typedef struct RegionInfo {
	ApplicableHeading_t	 applicableHeading;
	Position3D_t	 referencePoint;
	ReferencePointType_t	*referencePointType	/* OPTIONAL */;
	DescriptiveName_t	*descriptiveName	/* OPTIONAL */;
	struct RSMSpeedLimit	*speedLimit	/* OPTIONAL */;
	EventLength_t	*eventLength	/* OPTIONAL */;
	struct AreaType	*approachRegion	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_RegionInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_RegionInfo_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RSMSpeedLimit.h"
#include "AreaType.h"

#endif	/* _RegionInfo_H_ */
#include <asn_internal.h>
