/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "RegionInfo.h"

asn_TYPE_member_t asn_MBR_RegionInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RegionInfo, applicableHeading),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApplicableHeading,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"applicableHeading"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RegionInfo, referencePoint),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position3D,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referencePoint"
		},
	{ ATF_POINTER, 5, offsetof(struct RegionInfo, referencePointType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReferencePointType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referencePointType"
		},
	{ ATF_POINTER, 4, offsetof(struct RegionInfo, descriptiveName),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DescriptiveName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"descriptiveName"
		},
	{ ATF_POINTER, 3, offsetof(struct RegionInfo, speedLimit),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSMSpeedLimit,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speedLimit"
		},
	{ ATF_POINTER, 2, offsetof(struct RegionInfo, eventLength),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventLength,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventLength"
		},
	{ ATF_POINTER, 1, offsetof(struct RegionInfo, approachRegion),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AreaType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"approachRegion"
		},
};
static const int asn_MAP_RegionInfo_oms_1[] = { 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_RegionInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RegionInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* applicableHeadingat 59 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* referencePointat 60 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* referencePointTypeat 61 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* descriptiveNameat 62 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* speedLimitat 63 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* eventLengthat 64 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* approachRegionat 65 */
};
asn_SEQUENCE_specifics_t asn_SPC_RegionInfo_specs_1 = {
	sizeof(struct RegionInfo),
	offsetof(struct RegionInfo, _asn_ctx),
	asn_MAP_RegionInfo_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_RegionInfo_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RegionInfo = {
	"RegionInfo",
	"RegionInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_RegionInfo_tags_1,
	sizeof(asn_DEF_RegionInfo_tags_1)
		/sizeof(asn_DEF_RegionInfo_tags_1[0]), /* 1 */
	asn_DEF_RegionInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_RegionInfo_tags_1)
		/sizeof(asn_DEF_RegionInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RegionInfo_1,
	7,	/* Elements count */
	&asn_SPC_RegionInfo_specs_1	/* Additional specs */
};

