/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_201603DA-CAMP.ASN"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_RegionalExtension_H_
#define	_RegionalExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RegionId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "TestDataFrame-regExt.h"
#include "BasicSafetyMessage-regExt.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RegionalExtension_125P0__regExtValue_PR {
	RegionalExtension_125P0__regExtValue_PR_NOTHING,	/* No components present */
	RegionalExtension_125P0__regExtValue_PR_TestDataFrame_regExt,
	RegionalExtension_125P0__regExtValue_PR_BasicSafetyMessage_regExt
} RegionalExtension_125P0__regExtValue_PR;

/* RegionalExtension */
typedef struct RegionalExtension_125P0 {
	RegionId_t	 regionId;
	struct RegionalExtension_125P0__regExtValue {
		RegionalExtension_125P0__regExtValue_PR present;
		union RegionalExtension_125P0__regExtValue_u {
			TestDataFrame_regExt_t	 TestDataFrame_regExt;
			BasicSafetyMessage_regExt_t	 BasicSafetyMessage_regExt;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_125P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_125P0;
extern asn_SEQUENCE_specifics_t asn_SPC_RegionalExtension_125P0_specs_1;
extern asn_TYPE_member_t asn_MBR_RegionalExtension_125P0_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RegionalExtension_H_ */
#include <asn_internal.h>
