/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_RoadClosure_H_
#define	_RoadClosure_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ITIScodes.h"
#include "RegionInfo.h"
#include "MinutesDuration.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadClosure */
typedef struct RoadClosure {
	ITIScodes_t	 description;
	RegionInfo_t	 affectedLanes;
	MinutesDuration_t	*temporaryClosureDuration	/* OPTIONAL */;
	BOOLEAN_t	*indefiniteClosure	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadClosure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadClosure;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadClosure_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadClosure_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RoadClosure_H_ */
#include <asn_internal.h>
