/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "RoadsideSafetyMessage.h"

static int
memb_regional_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_regional_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_regional_constr_10 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_regional_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_regional_constr_10 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static int asn_DFL_2_cmp_1(const void *sptr) {
	const Version_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 1 */
	return (*st != 1);
}
static int asn_DFL_2_set_1(void **sptr) {
	Version_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 1 */
	*st = 1;
	return 0;
}
static asn_TYPE_member_t asn_MBR_regional_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RegionalExtension_125P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_regional_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_regional_specs_10 = {
	sizeof(struct RoadsideSafetyMessage__regional),
	offsetof(struct RoadsideSafetyMessage__regional, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_regional_10 = {
	"regional",
	"regional",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_regional_tags_10,
	sizeof(asn_DEF_regional_tags_10)
		/sizeof(asn_DEF_regional_tags_10[0]) - 1, /* 1 */
	asn_DEF_regional_tags_10,	/* Same as above */
	sizeof(asn_DEF_regional_tags_10)
		/sizeof(asn_DEF_regional_tags_10[0]), /* 2 */
	{ &asn_OER_type_regional_constr_10, &asn_PER_type_regional_constr_10, SEQUENCE_OF_constraint },
	asn_MBR_regional_10,
	1,	/* Single element */
	&asn_SPC_regional_specs_10	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RoadsideSafetyMessage_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RoadsideSafetyMessage, version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Version,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_1,	/* Compare DEFAULT 1 */
		&asn_DFL_2_set_1,	/* Set DEFAULT 1 */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoadsideSafetyMessage, commonContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CommonContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commonContainer"
		},
	{ ATF_POINTER, 7, offsetof(struct RoadsideSafetyMessage, rszContainer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReducedSpeedZoneContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rszContainer"
		},
	{ ATF_POINTER, 6, offsetof(struct RoadsideSafetyMessage, curveContainer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CurveContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"curveContainer"
		},
	{ ATF_POINTER, 5, offsetof(struct RoadsideSafetyMessage, staticSignageContainer),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StaticSignageContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"staticSignageContainer"
		},
	{ ATF_POINTER, 4, offsetof(struct RoadsideSafetyMessage, situationalContainer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SituationalContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"situationalContainer"
		},
	{ ATF_POINTER, 3, offsetof(struct RoadsideSafetyMessage, dynamicInfoContainer),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DynamicInfoContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dynamicInfoContainer"
		},
	{ ATF_POINTER, 2, offsetof(struct RoadsideSafetyMessage, incidentsContainer),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IncidentsContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"incidentsContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct RoadsideSafetyMessage, regional),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_regional_10,
		0,
		{ &asn_OER_memb_regional_constr_10, &asn_PER_memb_regional_constr_10,  memb_regional_constraint_1 },
		0, 0, /* No default value */
		"regional"
		},
};
static const int asn_MAP_RoadsideSafetyMessage_oms_1[] = { 0, 2, 3, 4, 5, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_RoadsideSafetyMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RoadsideSafetyMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* versionat 6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* commonContainerat 9 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rszContainerat 13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* curveContainerat 14 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* staticSignageContainerat 17 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* situationalContainerat 18 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* dynamicInfoContainerat 19 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* incidentsContainerat 20 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* regionalat 23 */
};
asn_SEQUENCE_specifics_t asn_SPC_RoadsideSafetyMessage_specs_1 = {
	sizeof(struct RoadsideSafetyMessage),
	offsetof(struct RoadsideSafetyMessage, _asn_ctx),
	asn_MAP_RoadsideSafetyMessage_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_RoadsideSafetyMessage_oms_1,	/* Optional members */
	8, 0,	/* Root/Additions */
	9,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RoadsideSafetyMessage = {
	"RoadsideSafetyMessage",
	"RoadsideSafetyMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_RoadsideSafetyMessage_tags_1,
	sizeof(asn_DEF_RoadsideSafetyMessage_tags_1)
		/sizeof(asn_DEF_RoadsideSafetyMessage_tags_1[0]), /* 1 */
	asn_DEF_RoadsideSafetyMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_RoadsideSafetyMessage_tags_1)
		/sizeof(asn_DEF_RoadsideSafetyMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RoadsideSafetyMessage_1,
	9,	/* Elements count */
	&asn_SPC_RoadsideSafetyMessage_specs_1	/* Additional specs */
};

