/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_RoadsideSafetyMessage_H_
#define	_RoadsideSafetyMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Version.h"
#include "CommonContainer.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReducedSpeedZoneContainer;
struct CurveContainer;
struct StaticSignageContainer;
struct SituationalContainer;
struct DynamicInfoContainer;
struct IncidentsContainer;
struct RegionalExtension;

/* RoadsideSafetyMessage */
typedef struct RoadsideSafetyMessage {
	Version_t	*version	/* DEFAULT 1 */;
	CommonContainer_t	 commonContainer;
	struct ReducedSpeedZoneContainer	*rszContainer	/* OPTIONAL */;
	struct CurveContainer	*curveContainer	/* OPTIONAL */;
	struct StaticSignageContainer	*staticSignageContainer	/* OPTIONAL */;
	struct SituationalContainer	*situationalContainer	/* OPTIONAL */;
	struct DynamicInfoContainer	*dynamicInfoContainer	/* OPTIONAL */;
	struct IncidentsContainer	*incidentsContainer	/* OPTIONAL */;
	struct RoadsideSafetyMessage__regional {
		A_SEQUENCE_OF(struct RegionalExtension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadsideSafetyMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadsideSafetyMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadsideSafetyMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadsideSafetyMessage_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReducedSpeedZoneContainer.h"
#include "CurveContainer.h"
#include "StaticSignageContainer.h"
#include "SituationalContainer.h"
#include "DynamicInfoContainer.h"
#include "IncidentsContainer.h"
#include "RegionalExtension.h"

#endif	/* _RoadsideSafetyMessage_H_ */
#include <asn_internal.h>
