/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "RSMLane.h"

static int
memb_connectsTo_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 16)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_connectsTo_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_connectsTo_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  1,  16 }	/* (SIZE(1..16,...)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_connectsTo_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_connectsTo_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  1,  16 }	/* (SIZE(1..16,...)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_connectsTo_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LaneID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_connectsTo_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_connectsTo_specs_7 = {
	sizeof(struct RSMLane__connectsTo),
	offsetof(struct RSMLane__connectsTo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connectsTo_7 = {
	"connectsTo",
	"connectsTo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_connectsTo_tags_7,
	sizeof(asn_DEF_connectsTo_tags_7)
		/sizeof(asn_DEF_connectsTo_tags_7[0]) - 1, /* 1 */
	asn_DEF_connectsTo_tags_7,	/* Same as above */
	sizeof(asn_DEF_connectsTo_tags_7)
		/sizeof(asn_DEF_connectsTo_tags_7[0]), /* 2 */
	{ &asn_OER_type_connectsTo_constr_7, &asn_PER_type_connectsTo_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_connectsTo_7,
	1,	/* Single element */
	&asn_SPC_connectsTo_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RSMLane_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RSMLane, laneID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneID"
		},
	{ ATF_POINTER, 5, offsetof(struct RSMLane, lanePosition),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LanePosition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lanePosition"
		},
	{ ATF_POINTER, 4, offsetof(struct RSMLane, laneName),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DescriptiveName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneName"
		},
	{ ATF_POINTER, 3, offsetof(struct RSMLane, laneWidth),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneWidth,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneWidth"
		},
	{ ATF_POINTER, 2, offsetof(struct RSMLane, laneGeometry),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LaneGeometry,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneGeometry"
		},
	{ ATF_POINTER, 1, offsetof(struct RSMLane, connectsTo),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_connectsTo_7,
		0,
		{ &asn_OER_memb_connectsTo_constr_7, &asn_PER_memb_connectsTo_constr_7,  memb_connectsTo_constraint_1 },
		0, 0, /* No default value */
		"connectsTo"
		},
};
static const int asn_MAP_RSMLane_oms_1[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_RSMLane_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RSMLane_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* laneIDat 146 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lanePositionat 147 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* laneNameat 148 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* laneWidthat 149 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* laneGeometryat 150 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* connectsToat 152 */
};
asn_SEQUENCE_specifics_t asn_SPC_RSMLane_specs_1 = {
	sizeof(struct RSMLane),
	offsetof(struct RSMLane, _asn_ctx),
	asn_MAP_RSMLane_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_RSMLane_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RSMLane = {
	"RSMLane",
	"RSMLane",
	&asn_OP_SEQUENCE,
	asn_DEF_RSMLane_tags_1,
	sizeof(asn_DEF_RSMLane_tags_1)
		/sizeof(asn_DEF_RSMLane_tags_1[0]), /* 1 */
	asn_DEF_RSMLane_tags_1,	/* Same as above */
	sizeof(asn_DEF_RSMLane_tags_1)
		/sizeof(asn_DEF_RSMLane_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RSMLane_1,
	6,	/* Elements count */
	&asn_SPC_RSMLane_specs_1	/* Additional specs */
};

