/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_RSMLane_H_
#define	_RSMLane_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneID.h"
#include "LanePosition.h"
#include "DescriptiveName.h"
#include "LaneWidth.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LaneGeometry;

/* RSMLane */
typedef struct RSMLane {
	LaneID_t	 laneID;
	LanePosition_t	*lanePosition	/* OPTIONAL */;
	DescriptiveName_t	*laneName	/* OPTIONAL */;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	struct LaneGeometry	*laneGeometry	/* OPTIONAL */;
	struct RSMLane__connectsTo {
		A_SEQUENCE_OF(LaneID_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *connectsTo;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RSMLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSMLane;
extern asn_SEQUENCE_specifics_t asn_SPC_RSMLane_specs_1;
extern asn_TYPE_member_t asn_MBR_RSMLane_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LaneGeometry.h"

#endif	/* _RSMLane_H_ */
#include <asn_internal.h>
