/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "RSMSpeedLimit.h"

static int asn_DFL_2_cmp_5(const void *sptr) {
	const SpeedLimitType_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 5 */
	return (*st != 5);
}
static int asn_DFL_2_set_5(void **sptr) {
	SpeedLimitType_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 5 */
	*st = 5;
	return 0;
}
static int asn_DFL_4_cmp_0(const void *sptr) {
	const SpeedUnits_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_4_set_0(void **sptr) {
	SpeedUnits_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
asn_TYPE_member_t asn_MBR_RSMSpeedLimit_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RSMSpeedLimit, type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedLimitType,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_5,	/* Compare DEFAULT 5 */
		&asn_DFL_2_set_5,	/* Set DEFAULT 5 */
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSMSpeedLimit, speed),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSM_Speed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speed"
		},
	{ ATF_NOFLAGS, 1, offsetof(struct RSMSpeedLimit, speedUnits),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedUnits,
		0,
		{ 0, 0, 0 },
		&asn_DFL_4_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_4_set_0,	/* Set DEFAULT 0 */
		"speedUnits"
		},
};
static const int asn_MAP_RSMSpeedLimit_oms_1[] = { 0, 2 };
static const ber_tlv_tag_t asn_DEF_RSMSpeedLimit_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RSMSpeedLimit_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* typeat 303 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* speedat 304 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* speedUnitsat 305 */
};
asn_SEQUENCE_specifics_t asn_SPC_RSMSpeedLimit_specs_1 = {
	sizeof(struct RSMSpeedLimit),
	offsetof(struct RSMSpeedLimit, _asn_ctx),
	asn_MAP_RSMSpeedLimit_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RSMSpeedLimit_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RSMSpeedLimit = {
	"RSMSpeedLimit",
	"RSMSpeedLimit",
	&asn_OP_SEQUENCE,
	asn_DEF_RSMSpeedLimit_tags_1,
	sizeof(asn_DEF_RSMSpeedLimit_tags_1)
		/sizeof(asn_DEF_RSMSpeedLimit_tags_1[0]), /* 1 */
	asn_DEF_RSMSpeedLimit_tags_1,	/* Same as above */
	sizeof(asn_DEF_RSMSpeedLimit_tags_1)
		/sizeof(asn_DEF_RSMSpeedLimit_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RSMSpeedLimit_1,
	3,	/* Elements count */
	&asn_SPC_RSMSpeedLimit_specs_1	/* Additional specs */
};

