/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_RSMSpeedLimit_H_
#define	_RSMSpeedLimit_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SpeedLimitType.h"
#include "RSM_Speed.h"
#include "SpeedUnits.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RSMSpeedLimit */
typedef struct RSMSpeedLimit {
	SpeedLimitType_t	*type	/* DEFAULT 5 */;
	RSM_Speed_t	 speed;
	SpeedUnits_t	 speedUnits	/* DEFAULT 0 */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RSMSpeedLimit_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSMSpeedLimit;
extern asn_SEQUENCE_specifics_t asn_SPC_RSMSpeedLimit_specs_1;
extern asn_TYPE_member_t asn_MBR_RSMSpeedLimit_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RSMSpeedLimit_H_ */
#include <asn_internal.h>
