/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNAL-APPROACH-SUPPLEMENTAL-INFORMATION-REGION"
 * 	found in "CAMP/SPAT_TOSCo_Regional_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "SignalPhaseTimingMessage-regExt.h"

/*
 * This type is implemented using GreenWindowInformation,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_SignalPhaseTimingMessage_regExt_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SignalPhaseTimingMessage_regExt = {
	"SignalPhaseTimingMessage-regExt",
	"SignalPhaseTimingMessage-regExt",
	&asn_OP_SEQUENCE,
	asn_DEF_SignalPhaseTimingMessage_regExt_tags_1,
	sizeof(asn_DEF_SignalPhaseTimingMessage_regExt_tags_1)
		/sizeof(asn_DEF_SignalPhaseTimingMessage_regExt_tags_1[0]), /* 1 */
	asn_DEF_SignalPhaseTimingMessage_regExt_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignalPhaseTimingMessage_regExt_tags_1)
		/sizeof(asn_DEF_SignalPhaseTimingMessage_regExt_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GreenWindowInformation_1,
	2,	/* Elements count */
	&asn_SPC_GreenWindowInformation_specs_1	/* Additional specs */
};

