/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "SituationalContainer.h"

static asn_oer_constraints_t asn_OER_type_SituationalContainer_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SituationalContainer_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SituationalContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SituationalContainer, choice.obstructions),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Obstructions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"obstructions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SituationalContainer, choice.overheightVehicle),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OverheightVehicle,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"overheightVehicle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SituationalContainer, choice.travelTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TravelTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"travelTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SituationalContainer, choice.roadClosure),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoadClosure,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"roadClosure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SituationalContainer, choice.railCrossing),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RailCrossing,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"railCrossing"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SituationalContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* obstructionsat 364 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* overheightVehicleat 365 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* travelTimeat 366 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* roadClosureat 367 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* railCrossingat 368 */
};
asn_CHOICE_specifics_t asn_SPC_SituationalContainer_specs_1 = {
	sizeof(struct SituationalContainer),
	offsetof(struct SituationalContainer, _asn_ctx),
	offsetof(struct SituationalContainer, present),
	sizeof(((struct SituationalContainer *)0)->present),
	asn_MAP_SituationalContainer_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SituationalContainer = {
	"SituationalContainer",
	"SituationalContainer",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SituationalContainer_constr_1, &asn_PER_type_SituationalContainer_constr_1, CHOICE_constraint },
	asn_MBR_SituationalContainer_1,
	5,	/* Elements count */
	&asn_SPC_SituationalContainer_specs_1	/* Additional specs */
};

