/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_StaticSignageContainer_H_
#define	_StaticSignageContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>
#include "MUTCDCode.h"
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RSMSpeedLimit;
struct GenericSignage;

/* StaticSignageContainer */
typedef struct StaticSignageContainer {
	struct RSMSpeedLimit	*speedLimit	/* OPTIONAL */;
	double	*mileMarker	/* OPTIONAL */;
	struct GenericSignage	*itisGenericSign	/* OPTIONAL */;
	MUTCDCode_t	*mutcdCode	/* OPTIONAL */;
	IA5String_t	*mutcdSignDesignation	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StaticSignageContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StaticSignageContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_StaticSignageContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_StaticSignageContainer_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RSMSpeedLimit.h"
#include "GenericSignage.h"

#endif	/* _StaticSignageContainer_H_ */
#include <asn_internal.h>
