/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_SurfaceCondition_H_
#define	_SurfaceCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SurfaceCondition {
	SurfaceCondition_dry	= 0,
	SurfaceCondition_moist	= 1,
	SurfaceCondition_wet	= 2,
	SurfaceCondition_flowing	= 3,
	SurfaceCondition_ice	= 4,
	SurfaceCondition_snow	= 5,
	SurfaceCondition_frost	= 6
	/*
	 * Enumeration is extensible
	 */
} e_SurfaceCondition;

/* SurfaceCondition */
typedef long	 SurfaceCondition_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SurfaceCondition_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SurfaceCondition;
extern const asn_INTEGER_specifics_t asn_SPC_SurfaceCondition_specs_1;
asn_struct_free_f SurfaceCondition_free;
asn_struct_print_f SurfaceCondition_print;
asn_constr_check_f SurfaceCondition_constraint;
ber_type_decoder_f SurfaceCondition_decode_ber;
der_type_encoder_f SurfaceCondition_encode_der;
xer_type_decoder_f SurfaceCondition_decode_xer;
xer_type_encoder_f SurfaceCondition_encode_xer;
oer_type_decoder_f SurfaceCondition_decode_oer;
oer_type_encoder_f SurfaceCondition_encode_oer;
per_type_decoder_f SurfaceCondition_decode_uper;
per_type_encoder_f SurfaceCondition_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SurfaceCondition_H_ */
#include <asn_internal.h>
