/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAMP-TESTING-REGION"
 * 	found in "CAMP/BSM_V2VI_TDF_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_TestDataFrameV2VI_H_
#define	_TestDataFrameV2VI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestDataFrameV2VI */
typedef struct TestDataFrameV2VI {
	OCTET_STRING_t	 obeIdentifier;
	long	 msgSequenceNumber;
	long	 testNumber;
	INTEGER_t	 preEncodingTimestamp;
	OCTET_STRING_t	 padBytes;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestDataFrameV2VI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestDataFrameV2VI;
extern asn_SEQUENCE_specifics_t asn_SPC_TestDataFrameV2VI_specs_1;
extern asn_TYPE_member_t asn_MBR_TestDataFrameV2VI_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _TestDataFrameV2VI_H_ */
#include <asn_internal.h>
