/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAMP-TESTING-REGION"
 * 	found in "CAMP/BSM_V2VI_TDF_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "TestDataFrameV2VI.h"

static int
memb_obeIdentifier_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_msgSequenceNumber_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_testNumber_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 99999999)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_preEncodingTimestamp_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 0 && value <= 253402300799999)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_padBytes_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 1000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_obeIdentifier_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	6	/* (SIZE(6..6)) */};
static asn_per_constraints_t asn_PER_memb_obeIdentifier_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  6,  6 }	/* (SIZE(6..6)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_msgSequenceNumber_constr_3 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_msgSequenceNumber_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_testNumber_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..99999999) */,
	-1};
static asn_per_constraints_t asn_PER_memb_testNumber_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 27, -1,  0,  99999999 }	/* (0..99999999) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_preEncodingTimestamp_constr_5 CC_NOTUSED = {
	{ 8, 1 }	/* (0..253402300799999) */,
	-1};
static asn_per_constraints_t asn_PER_memb_preEncodingTimestamp_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 48, -1,  0,  253402300799999 }	/* (0..253402300799999) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_padBytes_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..1000)) */};
static asn_per_constraints_t asn_PER_memb_padBytes_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 10,  10,  0,  1000 }	/* (SIZE(0..1000)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TestDataFrameV2VI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TestDataFrameV2VI, obeIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_obeIdentifier_constr_2, &asn_PER_memb_obeIdentifier_constr_2,  memb_obeIdentifier_constraint_1 },
		0, 0, /* No default value */
		"obeIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TestDataFrameV2VI, msgSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_msgSequenceNumber_constr_3, &asn_PER_memb_msgSequenceNumber_constr_3,  memb_msgSequenceNumber_constraint_1 },
		0, 0, /* No default value */
		"msgSequenceNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TestDataFrameV2VI, testNumber),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_testNumber_constr_4, &asn_PER_memb_testNumber_constr_4,  memb_testNumber_constraint_1 },
		0, 0, /* No default value */
		"testNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TestDataFrameV2VI, preEncodingTimestamp),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ &asn_OER_memb_preEncodingTimestamp_constr_5, &asn_PER_memb_preEncodingTimestamp_constr_5,  memb_preEncodingTimestamp_constraint_1 },
		0, 0, /* No default value */
		"preEncodingTimestamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TestDataFrameV2VI, padBytes),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_padBytes_constr_6, &asn_PER_memb_padBytes_constr_6,  memb_padBytes_constraint_1 },
		0, 0, /* No default value */
		"padBytes"
		},
};
static const ber_tlv_tag_t asn_DEF_TestDataFrameV2VI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TestDataFrameV2VI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* obeIdentifierat 9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* msgSequenceNumberat 10 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* testNumberat 11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* preEncodingTimestampat 12 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* padBytesat 14 */
};
asn_SEQUENCE_specifics_t asn_SPC_TestDataFrameV2VI_specs_1 = {
	sizeof(struct TestDataFrameV2VI),
	offsetof(struct TestDataFrameV2VI, _asn_ctx),
	asn_MAP_TestDataFrameV2VI_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TestDataFrameV2VI = {
	"TestDataFrameV2VI",
	"TestDataFrameV2VI",
	&asn_OP_SEQUENCE,
	asn_DEF_TestDataFrameV2VI_tags_1,
	sizeof(asn_DEF_TestDataFrameV2VI_tags_1)
		/sizeof(asn_DEF_TestDataFrameV2VI_tags_1[0]), /* 1 */
	asn_DEF_TestDataFrameV2VI_tags_1,	/* Same as above */
	sizeof(asn_DEF_TestDataFrameV2VI_tags_1)
		/sizeof(asn_DEF_TestDataFrameV2VI_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TestDataFrameV2VI_1,
	5,	/* Elements count */
	&asn_SPC_TestDataFrameV2VI_specs_1	/* Additional specs */
};

