/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "J2735_201603DA-CAMP.ASN"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "TimeMark-addGrpB.h"

static asn_TYPE_member_t asn_MBR_TimeMark_addGrpB_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, year),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Year,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"year"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, month),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Month,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"month"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, day),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Day,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"day"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, summerTime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SummerTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"summerTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, holiday),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Holiday,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"holiday"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, dayofWeek),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DayOfWeek,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dayofWeek"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, hour),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hour,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hour"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, minute),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Minute,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"minute"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, second),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Second,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"second"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeMark_addGrpB, tenthSecond),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TenthSecond,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tenthSecond"
		},
};
static const ber_tlv_tag_t asn_DEF_TimeMark_addGrpB_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TimeMark_addGrpB_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* yearat 5369 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* monthat 5370 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dayat 5371 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* summerTimeat 5372 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* holidayat 5373 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* dayofWeekat 5374 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* hourat 5375 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* minuteat 5376 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* secondat 5377 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* tenthSecondat 5379 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TimeMark_addGrpB_specs_1 = {
	sizeof(struct TimeMark_addGrpB),
	offsetof(struct TimeMark_addGrpB, _asn_ctx),
	asn_MAP_TimeMark_addGrpB_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TimeMark_addGrpB = {
	"TimeMark-addGrpB",
	"TimeMark-addGrpB",
	&asn_OP_SEQUENCE,
	asn_DEF_TimeMark_addGrpB_tags_1,
	sizeof(asn_DEF_TimeMark_addGrpB_tags_1)
		/sizeof(asn_DEF_TimeMark_addGrpB_tags_1[0]), /* 1 */
	asn_DEF_TimeMark_addGrpB_tags_1,	/* Same as above */
	sizeof(asn_DEF_TimeMark_addGrpB_tags_1)
		/sizeof(asn_DEF_TimeMark_addGrpB_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TimeMark_addGrpB_1,
	10,	/* Elements count */
	&asn_SPC_TimeMark_addGrpB_specs_1	/* Additional specs */
};

