/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_Tosco_H_
#define	_Tosco_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ToscoBehavior.h"
#include "LaneID.h"
#include "ToscoMode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntersectionReferenceID;

/* Tosco */
typedef struct Tosco {
	ToscoBehavior_t	 toscoBehavior	/* DEFAULT 0 */;
	struct IntersectionReferenceID	*approachingIntersection	/* OPTIONAL */;
	LaneID_t	*occupiedLane	/* OPTIONAL */;
	ToscoMode_t	*toscoMode	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Tosco_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Tosco;
extern asn_SEQUENCE_specifics_t asn_SPC_Tosco_specs_1;
extern asn_TYPE_member_t asn_MBR_Tosco_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IntersectionReferenceID.h"

#endif	/* _Tosco_H_ */
#include <asn_internal.h>
