/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "Tosco.h"

static int asn_DFL_2_cmp_0(const void *sptr) {
	const ToscoBehavior_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_2_set_0(void **sptr) {
	ToscoBehavior_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
asn_TYPE_member_t asn_MBR_Tosco_1[] = {
	{ ATF_NOFLAGS, 4, offsetof(struct Tosco, toscoBehavior),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ToscoBehavior,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_2_set_0,	/* Set DEFAULT 0 */
		"toscoBehavior"
		},
	{ ATF_POINTER, 3, offsetof(struct Tosco, approachingIntersection),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntersectionReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"approachingIntersection"
		},
	{ ATF_POINTER, 2, offsetof(struct Tosco, occupiedLane),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"occupiedLane"
		},
	{ ATF_POINTER, 1, offsetof(struct Tosco, toscoMode),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ToscoMode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"toscoMode"
		},
};
static const int asn_MAP_Tosco_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_Tosco_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Tosco_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* toscoBehaviorat 34 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* approachingIntersectionat 35 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* occupiedLaneat 36 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* toscoModeat 37 */
};
asn_SEQUENCE_specifics_t asn_SPC_Tosco_specs_1 = {
	sizeof(struct Tosco),
	offsetof(struct Tosco, _asn_ctx),
	asn_MAP_Tosco_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Tosco_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Tosco = {
	"Tosco",
	"Tosco",
	&asn_OP_SEQUENCE,
	asn_DEF_Tosco_tags_1,
	sizeof(asn_DEF_Tosco_tags_1)
		/sizeof(asn_DEF_Tosco_tags_1[0]), /* 1 */
	asn_DEF_Tosco_tags_1,	/* Same as above */
	sizeof(asn_DEF_Tosco_tags_1)
		/sizeof(asn_DEF_Tosco_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Tosco_1,
	4,	/* Elements count */
	&asn_SPC_Tosco_specs_1	/* Additional specs */
};

