/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "ToscoMode.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ToscoMode_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ToscoMode_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  9 }	/* (0..9,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ToscoMode_value2enum_1[] = {
	{ 0,	9,	"free-flow" },
	{ 1,	25,	"coordinated-speed-control" },
	{ 2,	16,	"optimized-follow" },
	{ 3,	16,	"coordinated-stop" },
	{ 4,	7,	"stopped" },
	{ 5,	5,	"creep" },
	{ 6,	18,	"coordinated-launch" },
	{ 7,	34,	"coordinated-speed-control-constant" },
	{ 8,	34,	"coordinated-speed-control-speed-up" },
	{ 9,	35,	"coordinated-speed-control-slow-down" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ToscoMode_enum2value_1[] = {
	6,	/* coordinated-launch(6) */
	1,	/* coordinated-speed-control(1) */
	7,	/* coordinated-speed-control-constant(7) */
	9,	/* coordinated-speed-control-slow-down(9) */
	8,	/* coordinated-speed-control-speed-up(8) */
	3,	/* coordinated-stop(3) */
	5,	/* creep(5) */
	0,	/* free-flow(0) */
	2,	/* optimized-follow(2) */
	4	/* stopped(4) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_ToscoMode_specs_1 = {
	asn_MAP_ToscoMode_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ToscoMode_enum2value_1,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	11,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ToscoMode_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ToscoMode = {
	"ToscoMode",
	"ToscoMode",
	&asn_OP_NativeEnumerated,
	asn_DEF_ToscoMode_tags_1,
	sizeof(asn_DEF_ToscoMode_tags_1)
		/sizeof(asn_DEF_ToscoMode_tags_1[0]), /* 1 */
	asn_DEF_ToscoMode_tags_1,	/* Same as above */
	sizeof(asn_DEF_ToscoMode_tags_1)
		/sizeof(asn_DEF_ToscoMode_tags_1[0]), /* 1 */
	{ &asn_OER_type_ToscoMode_constr_1, &asn_PER_type_ToscoMode_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ToscoMode_specs_1	/* Additional specs */
};

