/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LONGITUDINAL-CONTROL-TESTING-REGION"
 * 	found in "CAMP/BSM_TOSCo_CACC_Extension.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_ToscoMode_H_
#define	_ToscoMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ToscoMode {
	ToscoMode_free_flow	= 0,
	ToscoMode_coordinated_speed_control	= 1,
	ToscoMode_optimized_follow	= 2,
	ToscoMode_coordinated_stop	= 3,
	ToscoMode_stopped	= 4,
	ToscoMode_creep	= 5,
	ToscoMode_coordinated_launch	= 6,
	ToscoMode_coordinated_speed_control_constant	= 7,
	ToscoMode_coordinated_speed_control_speed_up	= 8,
	ToscoMode_coordinated_speed_control_slow_down	= 9
	/*
	 * Enumeration is extensible
	 */
} e_ToscoMode;

/* ToscoMode */
typedef long	 ToscoMode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ToscoMode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ToscoMode;
extern const asn_INTEGER_specifics_t asn_SPC_ToscoMode_specs_1;
asn_struct_free_f ToscoMode_free;
asn_struct_print_f ToscoMode_print;
asn_constr_check_f ToscoMode_constraint;
ber_type_decoder_f ToscoMode_decode_ber;
der_type_encoder_f ToscoMode_encode_der;
xer_type_decoder_f ToscoMode_decode_xer;
xer_type_encoder_f ToscoMode_encode_xer;
oer_type_decoder_f ToscoMode_decode_oer;
oer_type_encoder_f ToscoMode_encode_oer;
per_type_decoder_f ToscoMode_decode_uper;
per_type_encoder_f ToscoMode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ToscoMode_H_ */
#include <asn_internal.h>
