/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#ifndef	_TypeOfDynamicInfo_H_
#define	_TypeOfDynamicInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TypeOfDynamicInfo {
	TypeOfDynamicInfo_road_work	= 0,
	TypeOfDynamicInfo_road_closure	= 1,
	TypeOfDynamicInfo_travel_time	= 2,
	TypeOfDynamicInfo_congestion	= 3,
	TypeOfDynamicInfo_incident	= 4,
	TypeOfDynamicInfo_obstruction	= 5,
	TypeOfDynamicInfo_weather_alert	= 6,
	TypeOfDynamicInfo_special_event	= 7
	/*
	 * Enumeration is extensible
	 */
} e_TypeOfDynamicInfo;

/* TypeOfDynamicInfo */
typedef long	 TypeOfDynamicInfo_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TypeOfDynamicInfo_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TypeOfDynamicInfo;
extern const asn_INTEGER_specifics_t asn_SPC_TypeOfDynamicInfo_specs_1;
asn_struct_free_f TypeOfDynamicInfo_free;
asn_struct_print_f TypeOfDynamicInfo_print;
asn_constr_check_f TypeOfDynamicInfo_constraint;
ber_type_decoder_f TypeOfDynamicInfo_decode_ber;
der_type_encoder_f TypeOfDynamicInfo_encode_der;
xer_type_decoder_f TypeOfDynamicInfo_decode_xer;
xer_type_encoder_f TypeOfDynamicInfo_encode_xer;
oer_type_decoder_f TypeOfDynamicInfo_decode_oer;
oer_type_encoder_f TypeOfDynamicInfo_encode_oer;
per_type_decoder_f TypeOfDynamicInfo_decode_uper;
per_type_encoder_f TypeOfDynamicInfo_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TypeOfDynamicInfo_H_ */
#include <asn_internal.h>
