/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM/rsmv5.1.asn"
 * 	`asn1c -D src -gen-PER -pdu=MessageFrame -fcompound-names -fline-refs -no-gen-example`
 */

#include "TypeOfDynamicInfo.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_TypeOfDynamicInfo_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TypeOfDynamicInfo_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  7 }	/* (0..7,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_TypeOfDynamicInfo_value2enum_1[] = {
	{ 0,	9,	"road-work" },
	{ 1,	12,	"road-closure" },
	{ 2,	11,	"travel-time" },
	{ 3,	10,	"congestion" },
	{ 4,	8,	"incident" },
	{ 5,	11,	"obstruction" },
	{ 6,	13,	"weather-alert" },
	{ 7,	13,	"special-event" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_TypeOfDynamicInfo_enum2value_1[] = {
	3,	/* congestion(3) */
	4,	/* incident(4) */
	5,	/* obstruction(5) */
	1,	/* road-closure(1) */
	0,	/* road-work(0) */
	7,	/* special-event(7) */
	2,	/* travel-time(2) */
	6	/* weather-alert(6) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_TypeOfDynamicInfo_specs_1 = {
	asn_MAP_TypeOfDynamicInfo_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_TypeOfDynamicInfo_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	9,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_TypeOfDynamicInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_TypeOfDynamicInfo = {
	"TypeOfDynamicInfo",
	"TypeOfDynamicInfo",
	&asn_OP_NativeEnumerated,
	asn_DEF_TypeOfDynamicInfo_tags_1,
	sizeof(asn_DEF_TypeOfDynamicInfo_tags_1)
		/sizeof(asn_DEF_TypeOfDynamicInfo_tags_1[0]), /* 1 */
	asn_DEF_TypeOfDynamicInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_TypeOfDynamicInfo_tags_1)
		/sizeof(asn_DEF_TypeOfDynamicInfo_tags_1[0]), /* 1 */
	{ &asn_OER_type_TypeOfDynamicInfo_constr_1, &asn_PER_type_TypeOfDynamicInfo_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_TypeOfDynamicInfo_specs_1	/* Additional specs */
};

